商品情報一覧の並び順セレクトタグが検索ボタンを押さないと動かなかったのでjsを追記
ecsite-project/ec-202404a pull request #76
Opened 2024-06-19 09:05 UTC by krkrHotaru

ブランチ名が非同期じゃないのに非同期処理になってるのはゆるして

2024-06-19 17:01 UTC, Ruii1112 requested changes
レビューしました。対応よろしくお願いします。

2024-06-19 17:01 UTC, Ruii1112 commented on src/main/resources/static/js/item-list/autoComp.js
> +      type: 'POST',
403エラー出ない？

2024-06-19 17:01 UTC, Ruii1112 commented on src/main/resources/templates/item-list.html
> +    <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.js"></script>
jqueryのuiは上の方が良いかも。
あと、cssって入れないっけ？

2024-06-20 02:25 UTC, sumiship approved these changes
良いと思います！

2024-06-20 02:30 UTC, Ruii1112 approved these changes
すみがokと言ってた

2024-06-20 02:30 UTC, merged